version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: LoyaltyCard
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/LoyaltyCard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASS}
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge