spring:
  application:
    name: LoyaltyCard
  datasource:
    url: jdbc:postgresql://localhost:5432/LoyaltyCard
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
